/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DependenteController;
import controller.EmpregadoController;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import negocio.Dependente;
import negocio.Empregado;

/**
 *
 * @author RAFAEL
 */
public class FrmDependente extends javax.swing.JFrame {

    private List<Empregado> listaEmp;
    MaskFormatter mascaraData;

    /**
     * Creates new form FrmDependente
     */
    public FrmDependente() {
        try {
            mascaraData = new MaskFormatter("##/##/####");
        } catch (ParseException e2) {
            System.err.println(e2.getMessage());
        }
        initComponents();
        EmpregadoController controller = new EmpregadoController();
        listaEmp = controller.listarTodos();
        for (Empregado e : listaEmp) {
            System.out.println(e.getNome());
            boxDepEmpregado.addItem(e.getNome());
        }
        boxGrauParentesco.addItem("Filho(a)");
        boxGrauParentesco.addItem("Pai");
        boxGrauParentesco.addItem("Mãe");
        boxGrauParentesco.addItem("Cônjuge");
        DefaultTableModel tbm = (DefaultTableModel) tblDependentes.getModel();
        for (int i = tbm.getRowCount() - 1; i >= 0; i--) {
            tbm.removeRow(i);
        }
        
    }

    public void mostraDados() {
        List<Dependente> listaDep = new ArrayList<>();
        DependenteController controller = new DependenteController();
        listaDep = controller.listarTodos();
        DefaultTableModel tbm = (DefaultTableModel) tblDependentes.getModel();

        for (int i = tbm.getRowCount() - 1; i >= 0; i--) {
            tbm.removeRow(i);
        }
        int i = 0;
        for (Dependente dp : listaDep) {
            tbm.addRow(new String[1]);
            tblDependentes.setValueAt(dp.getCpfEmpregado(), i, 0);
            tblDependentes.setValueAt(dp.getNome(), i, 1);
            tblDependentes.setValueAt(dp.getGrauParentesco(), i, 2);
            tblDependentes.setValueAt(dp.getDataNascimento(), i, 3);
            i++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblDepMsg = new javax.swing.JLabel();
        boxDepEmpregado = new javax.swing.JComboBox<>();
        btnRet = new javax.swing.JButton();
        txtDepNome = new javax.swing.JTextField();
        fTxtData = new JFormattedTextField(mascaraData);
        jLabel7 = new javax.swing.JLabel();
        boxGrauParentesco = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnDepInserir = new javax.swing.JButton();
        btnDepAlterar = new javax.swing.JButton();
        btnDepExcluir = new javax.swing.JButton();
        btnDepPesquisar = new javax.swing.JButton();
        btnDepLimpar = new javax.swing.JButton();
        btnDepSair = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDependentes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Empregado:");

        jLabel2.setText("Nome:");

        jLabel3.setText("Grau de Parentesco:");

        jLabel4.setText("Data de Nascimento:");

        jLabel5.setText("Mensagem:");

        boxDepEmpregado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        btnRet.setText("...");
        btnRet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetActionPerformed(evt);
            }
        });

        jLabel7.setText("dd/mm/aaaa");

        boxGrauParentesco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(boxDepEmpregado, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRet))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(fTxtData, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDepMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(boxGrauParentesco, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(txtDepNome, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 211, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(boxDepEmpregado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRet))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDepNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(boxGrauParentesco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fTxtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(lblDepMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnDepInserir.setText("Inserir");
        btnDepInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepInserirActionPerformed(evt);
            }
        });

        btnDepAlterar.setText("Alterar");
        btnDepAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepAlterarActionPerformed(evt);
            }
        });

        btnDepExcluir.setText("Excluir");
        btnDepExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepExcluirActionPerformed(evt);
            }
        });

        btnDepPesquisar.setText("Pesquisar");
        btnDepPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepPesquisarActionPerformed(evt);
            }
        });

        btnDepLimpar.setText("Limpar");
        btnDepLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepLimparActionPerformed(evt);
            }
        });

        btnDepSair.setText("Sair");
        btnDepSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDepInserir)
                .addGap(18, 18, 18)
                .addComponent(btnDepAlterar)
                .addGap(18, 18, 18)
                .addComponent(btnDepExcluir)
                .addGap(18, 18, 18)
                .addComponent(btnDepPesquisar)
                .addGap(18, 18, 18)
                .addComponent(btnDepLimpar)
                .addGap(18, 18, 18)
                .addComponent(btnDepSair)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDepInserir)
                    .addComponent(btnDepAlterar)
                    .addComponent(btnDepExcluir)
                    .addComponent(btnDepPesquisar)
                    .addComponent(btnDepLimpar)
                    .addComponent(btnDepSair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblDependentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Empregado", "Nome", "Grau de Parentesco", "Data de Nascimento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDependentes.getTableHeader().setReorderingAllowed(false);
        tblDependentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDependentesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDependentes);
        if (tblDependentes.getColumnModel().getColumnCount() > 0) {
            tblDependentes.getColumnModel().getColumn(0).setResizable(false);
            tblDependentes.getColumnModel().getColumn(1).setResizable(false);
            tblDependentes.getColumnModel().getColumn(2).setResizable(false);
            tblDependentes.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDepInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepInserirActionPerformed
        Dependente dep = new Dependente();
        DependenteController controller = new DependenteController();
        Integer pos = 0;
        for (Empregado e1 : listaEmp) {
            if (e1.getNome().equals(boxDepEmpregado.getSelectedItem())) {
                pos = listaEmp.indexOf(e1);
            }
        }
        dep.setCpfEmpregado(listaEmp.get(pos).getCpf());
        dep.setNome(txtDepNome.getText());
        dep.setGrauParentesco(boxGrauParentesco.getSelectedItem().toString());
        SimpleDateFormat sfPostgres = new SimpleDateFormat("dd/MM/yyyy");
        String sDataNasc = fTxtData.getText();
        try {
            dep.setDataNascimento(sfPostgres.parse(sDataNasc));
        } catch (ParseException e) {
            lblDepMsg.setText(e.getMessage());
        }
        lblDepMsg.setText(controller.inserir(dep));
        mostraDados();
    }//GEN-LAST:event_btnDepInserirActionPerformed

    private void btnDepLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepLimparActionPerformed
        txtDepNome.setText("");
        fTxtData.setText("");
        lblDepMsg.setText("");
        boxGrauParentesco.setSelectedIndex(0);
        boxDepEmpregado.setSelectedIndex(0);
        DefaultTableModel tbm = (DefaultTableModel) tblDependentes.getModel();
        for (int i = tbm.getRowCount() - 1; i >= 0; i--) {
            tbm.removeRow(i);
        }
    }//GEN-LAST:event_btnDepLimparActionPerformed

    private void btnDepSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepSairActionPerformed
        FrmDependente.this.dispose();
    }//GEN-LAST:event_btnDepSairActionPerformed

    private void tblDependentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDependentesMouseClicked
        Integer linha = tblDependentes.getSelectedRow();
        String cpfDependente = tblDependentes.getValueAt(linha, 0).toString();
        String nome = tblDependentes.getValueAt(linha, 1).toString();
        String grauParente = tblDependentes.getValueAt(linha, 2).toString();
        String dataNasc = tblDependentes.getValueAt(linha, 3).toString();

        txtDepNome.setText(nome);
        boxGrauParentesco.setSelectedItem(grauParente);
        fTxtData.setText(dataNasc);
        Integer pos = 0;

        for (Empregado e1 : listaEmp) {
            if (e1.getCpf().equals(tblDependentes.getValueAt(linha, 0).toString())) {
                pos = listaEmp.indexOf(e1);
            }
            boxDepEmpregado.setSelectedItem(listaEmp.get(pos).getNome());
        }
    }//GEN-LAST:event_tblDependentesMouseClicked

    private void btnDepPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepPesquisarActionPerformed
        mostraDados();
    }//GEN-LAST:event_btnDepPesquisarActionPerformed

    private void btnDepAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepAlterarActionPerformed
        Dependente dep = new Dependente();
        DependenteController controller = new DependenteController();
        Integer pos = 0;

        for (Empregado e1 : listaEmp) {
            if (e1.getNome().equals(boxDepEmpregado.getSelectedItem())) {
                pos = listaEmp.indexOf(e1);
            }
        }

        dep.setCpfEmpregado(listaEmp.get(pos).getCpf());
        dep.setNome(txtDepNome.getText());
        dep.setGrauParentesco(boxGrauParentesco.getSelectedItem().toString());
        SimpleDateFormat sfPostgres = new SimpleDateFormat("dd/MM/yyyy");
        try {
            dep.setDataNascimento(sfPostgres.parse(fTxtData.getText()));
        } catch (ParseException e1) {
            lblDepMsg.setText(e1.getMessage());
        }
        lblDepMsg.setText(controller.alterar(dep));
        mostraDados();
    }//GEN-LAST:event_btnDepAlterarActionPerformed

    private void btnDepExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepExcluirActionPerformed
        Dependente dep = new Dependente();
        DependenteController controller = new DependenteController();
        Integer pos = 0;
        for (Empregado e1 : listaEmp) {
            if (e1.getNome().equals(boxDepEmpregado.getSelectedItem())) {
                pos = listaEmp.indexOf(e1);
            }
        }
        dep.setCpfEmpregado(listaEmp.get(pos).getCpf());
        dep.setNome(txtDepNome.getText());
        Object[] opcoes = {"SIM", "Não"};
        int escolha
                = JOptionPane.showOptionDialog(null, "Deseja excluir: "
                        + txtDepNome.getText(), "Exclusão",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[0]);
        if (escolha == JOptionPane.YES_OPTION) {
            lblDepMsg.setText(controller.excluir(dep));
        }
        mostraDados();
    }//GEN-LAST:event_btnDepExcluirActionPerformed

    private void btnRetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetActionPerformed
        FrmEmpregado fe = new FrmEmpregado();
        fe.pack();
        fe.setVisible(true);
    }//GEN-LAST:event_btnRetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDependente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDependente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDependente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDependente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDependente().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxDepEmpregado;
    private javax.swing.JComboBox<String> boxGrauParentesco;
    private javax.swing.JButton btnDepAlterar;
    private javax.swing.JButton btnDepExcluir;
    private javax.swing.JButton btnDepInserir;
    private javax.swing.JButton btnDepLimpar;
    private javax.swing.JButton btnDepPesquisar;
    private javax.swing.JButton btnDepSair;
    private javax.swing.JButton btnRet;
    private javax.swing.JFormattedTextField fTxtData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDepMsg;
    private javax.swing.JTable tblDependentes;
    private javax.swing.JTextField txtDepNome;
    // End of variables declaration//GEN-END:variables
}
